
version: 2

models:
  - name: eth_raw
    description: "bronze layer"
    columns:
      - name: BLOCK_HASH
        description: "The primary key for this table"
        tests:
          - not_null

